server: "54.179.163.116:50051"
connect_timeout: 30
working_directory: "/opt/cloudsec/agent/data/agent"
plugins_directory: "/opt/cloudsec/agent/plugins"
log_directory: "/opt/cloudsec/agent/logs"
retry_max_count: 10
retry_interval: 5
