// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.5
// source: proto/grpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PackagedData Agent 发送给 Server 的数据包
type PackagedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*EncodedRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`                      // 编码后的数据记录列表
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`       // Agent 唯一标识符
	Ipv4          []string               `protobuf:"bytes,3,rep,name=ipv4,proto3" json:"ipv4,omitempty"`                            // IPv4 地址列表
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`                    // 主机名
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                      // Agent 版本号
	Product       string                 `protobuf:"bytes,6,opt,name=product,proto3" json:"product,omitempty"`                      // 产品名称
	MacAddr       string                 `protobuf:"bytes,7,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`       // MAC 地址
	OsType        string                 `protobuf:"bytes,8,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`          // 操作系统类型 (linux/windows)
	OsVersion     string                 `protobuf:"bytes,9,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"` // 操作系统版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagedData) Reset() {
	*x = PackagedData{}
	mi := &file_proto_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagedData) ProtoMessage() {}

func (x *PackagedData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagedData.ProtoReflect.Descriptor instead.
func (*PackagedData) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *PackagedData) GetRecords() []*EncodedRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *PackagedData) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PackagedData) GetIpv4() []string {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *PackagedData) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PackagedData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackagedData) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *PackagedData) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

func (x *PackagedData) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *PackagedData) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

// EncodedRecord 编码后的记录（用于传输）
type EncodedRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      int32                  `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // 数据类型
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // 时间戳
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                          // 序列化后的数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodedRecord) Reset() {
	*x = EncodedRecord{}
	mi := &file_proto_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedRecord) ProtoMessage() {}

func (x *EncodedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedRecord.ProtoReflect.Descriptor instead.
func (*EncodedRecord) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *EncodedRecord) GetDataType() int32 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *EncodedRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EncodedRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Record 未编码的记录（Agent 内部使用）
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      int32                  `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // 数据类型
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // 时间戳
	Data          *Payload               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                          // 结构化的数据负载
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Record) GetDataType() int32 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *Record) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Record) GetData() *Payload {
	if x != nil {
		return x.Data
	}
	return nil
}

// Payload 数据负载（键值对格式）
type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 字段映射
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *Payload) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Command Server 下发给 Agent 的命令
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctrl          int32                  `protobuf:"varint,1,opt,name=ctrl,proto3" json:"ctrl,omitempty"`      // 控制字段
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`       // 任务（可选）
	Configs       []*Config              `protobuf:"bytes,3,rep,name=configs,proto3" json:"configs,omitempty"` // 插件配置列表（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetCtrl() int32 {
	if x != nil {
		return x.Ctrl
	}
	return 0
}

func (x *Command) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *Command) GetConfigs() []*Config {
	if x != nil {
		return x.Configs
	}
	return nil
}

// Task 任务结构
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      int32                  `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`      // 任务数据类型
	ObjectName    string                 `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"` // 目标对象名称（Agent 或插件名称）
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                               // 任务数据（JSON 格式）
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                             // 任务令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetDataType() int32 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *Task) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *Task) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Task) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Config 插件配置
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // 插件名称
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                     // 插件类型
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                               // 插件版本号
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`                                 // SHA256 校验值
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                           // 插件签名
	DownloadUrls  []string               `protobuf:"bytes,6,rep,name=download_urls,json=downloadUrls,proto3" json:"download_urls,omitempty"` // 下载地址列表
	Detail        string                 `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`                                 // 详细信息（JSON 格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proto_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Config) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Config) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Config) GetDownloadUrls() []string {
	if x != nil {
		return x.DownloadUrls
	}
	return nil
}

func (x *Config) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_proto_grpc_proto protoreflect.FileDescriptor

const file_proto_grpc_proto_rawDesc = "" +
	"\n" +
	"\x10proto/grpc.proto\x12\x04grpc\"\x8f\x02\n" +
	"\fPackagedData\x12-\n" +
	"\arecords\x18\x01 \x03(\v2\x13.grpc.EncodedRecordR\arecords\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04ipv4\x18\x03 \x03(\tR\x04ipv4\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x18\n" +
	"\aproduct\x18\x06 \x01(\tR\aproduct\x12\x19\n" +
	"\bmac_addr\x18\a \x01(\tR\amacAddr\x12\x17\n" +
	"\aos_type\x18\b \x01(\tR\x06osType\x12\x1d\n" +
	"\n" +
	"os_version\x18\t \x01(\tR\tosVersion\"^\n" +
	"\rEncodedRecord\x12\x1b\n" +
	"\tdata_type\x18\x01 \x01(\x05R\bdataType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"f\n" +
	"\x06Record\x12\x1b\n" +
	"\tdata_type\x18\x01 \x01(\x05R\bdataType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.grpc.PayloadR\x04data\"w\n" +
	"\aPayload\x121\n" +
	"\x06fields\x18\x01 \x03(\v2\x19.grpc.Payload.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\aCommand\x12\x12\n" +
	"\x04ctrl\x18\x01 \x01(\x05R\x04ctrl\x12\x1e\n" +
	"\x04task\x18\x02 \x01(\v2\n" +
	".grpc.TaskR\x04task\x12&\n" +
	"\aconfigs\x18\x03 \x03(\v2\f.grpc.ConfigR\aconfigs\"n\n" +
	"\x04Task\x12\x1b\n" +
	"\tdata_type\x18\x01 \x01(\x05R\bdataType\x12\x1f\n" +
	"\vobject_name\x18\x02 \x01(\tR\n" +
	"objectName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\xbd\x01\n" +
	"\x06Config\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12#\n" +
	"\rdownload_urls\x18\x06 \x03(\tR\fdownloadUrls\x12\x16\n" +
	"\x06detail\x18\a \x01(\tR\x06detail2?\n" +
	"\bTransfer\x123\n" +
	"\bTransfer\x12\x12.grpc.PackagedData\x1a\r.grpc.Command\"\x00(\x010\x01B\x16Z\x14company/server/protob\x06proto3"

var (
	file_proto_grpc_proto_rawDescOnce sync.Once
	file_proto_grpc_proto_rawDescData []byte
)

func file_proto_grpc_proto_rawDescGZIP() []byte {
	file_proto_grpc_proto_rawDescOnce.Do(func() {
		file_proto_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpc_proto_rawDesc), len(file_proto_grpc_proto_rawDesc)))
	})
	return file_proto_grpc_proto_rawDescData
}

var file_proto_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_grpc_proto_goTypes = []any{
	(*PackagedData)(nil),  // 0: grpc.PackagedData
	(*EncodedRecord)(nil), // 1: grpc.EncodedRecord
	(*Record)(nil),        // 2: grpc.Record
	(*Payload)(nil),       // 3: grpc.Payload
	(*Command)(nil),       // 4: grpc.Command
	(*Task)(nil),          // 5: grpc.Task
	(*Config)(nil),        // 6: grpc.Config
	nil,                   // 7: grpc.Payload.FieldsEntry
}
var file_proto_grpc_proto_depIdxs = []int32{
	1, // 0: grpc.PackagedData.records:type_name -> grpc.EncodedRecord
	3, // 1: grpc.Record.data:type_name -> grpc.Payload
	7, // 2: grpc.Payload.fields:type_name -> grpc.Payload.FieldsEntry
	5, // 3: grpc.Command.task:type_name -> grpc.Task
	6, // 4: grpc.Command.configs:type_name -> grpc.Config
	0, // 5: grpc.Transfer.Transfer:input_type -> grpc.PackagedData
	4, // 6: grpc.Transfer.Transfer:output_type -> grpc.Command
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_grpc_proto_init() }
func file_proto_grpc_proto_init() {
	if File_proto_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpc_proto_rawDesc), len(file_proto_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpc_proto_goTypes,
		DependencyIndexes: file_proto_grpc_proto_depIdxs,
		MessageInfos:      file_proto_grpc_proto_msgTypes,
	}.Build()
	File_proto_grpc_proto = out.File
	file_proto_grpc_proto_goTypes = nil
	file_proto_grpc_proto_depIdxs = nil
}
