// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfAcceptEvent struct {
	EventType  uint8
	Protocol   uint8
	Padding1   [2]uint8
	Pid        uint32
	Tgid       uint32
	Ppid       uint32
	Uid        uint32
	RemoteIp   uint32
	RemotePort uint16
	LocalPort  uint16
	LocalIp    uint32
	Retval     int32
	Comm       [16]int8
	ExePath    [256]int8
}

type bpfBindEvent struct {
	EventType uint8
	Protocol  uint8
	Padding1  [2]uint8
	Pid       uint32
	Tgid      uint32
	Ppid      uint32
	Uid       uint32
	BindIp    uint32
	BindPort  uint16
	Padding2  uint16
	Retval    int32
	Comm      [16]int8
	ExePath   [256]int8
}

type bpfCommitCredsEvent struct {
	EventType uint8
	Padding1  [3]uint8
	Pid       uint32
	Tgid      uint32
	Ppid      uint32
	Uid       uint32
	OldUid    uint32
	OldEuid   uint32
	NewUid    uint32
	NewEuid   uint32
	Comm      [16]int8
	ExePath   [256]int8
}

type bpfConnectEvent struct {
	EventType  uint8
	Protocol   uint8
	Padding1   [2]uint8
	Pid        uint32
	Tgid       uint32
	Ppid       uint32
	Uid        uint32
	RemoteIp   uint32
	RemotePort uint16
	LocalPort  uint16
	LocalIp    uint32
	Retval     int32
	Comm       [16]int8
	ExePath    [256]int8
}

type bpfDnsDataBuf struct{ Data [512]int8 }

type bpfDnsEvent struct {
	EventType     uint8
	Padding1      [3]uint8
	Pid           uint32
	Tgid          uint32
	Ppid          uint32
	Uid           uint32
	DnsServerIp   uint32
	DnsServerPort uint16
	QueryType     uint16
	Opcode        int32
	Rcode         int32
	Comm          [16]int8
	ExePath       [256]int8
	Domain        [256]int8
}

type bpfExeItem struct {
	Len  int32
	Sid  uint32
	Hash uint64
	Name [2048]int8
}

type bpfExecveEvent struct {
	EventType  uint8
	FdType     uint8
	Padding1   [2]uint8
	Pid        uint32
	Tgid       uint32
	Ppid       uint32
	Pgid       uint32
	Uid        uint32
	SocketPid  uint32
	Comm       [16]int8
	ExePath    [256]int8
	Args       [512]int8
	StdinPath  [64]int8
	StdoutPath [64]int8
	TtyName    [64]int8
	RemoteIp   uint32
	RemotePort uint16
	LocalPort  uint16
	LocalIp    uint32
}

type bpfFileEvent struct {
	EventType  uint8
	Action     uint8
	Padding1   [2]uint8
	Pid        uint32
	Tgid       uint32
	Ppid       uint32
	Uid        uint32
	SocketPid  uint32
	RemoteIp   uint32
	RemotePort uint16
	LocalPort  uint16
	LocalIp    uint32
	Comm       [16]int8
	ExePath    [256]int8
	NewPath    [512]int8
	OldPath    [512]int8
	S_id       [32]int8
}

type bpfPathBuf struct {
	Data [512]int8
	Swap [260]int8
}

type bpfStdioPathBuf struct {
	Data [512]int8
	Swap [260]int8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KpCommitCreds *ebpf.ProgramSpec `ebpf:"kp_commit_creds"`
	KpInodeCreate *ebpf.ProgramSpec `ebpf:"kp_inode_create"`
	KpInodeRename *ebpf.ProgramSpec `ebpf:"kp_inode_rename"`
	KpInodeUnlink *ebpf.ProgramSpec `ebpf:"kp_inode_unlink"`
	TpProcExec    *ebpf.ProgramSpec `ebpf:"tp_proc_exec"`
	TpSysExit     *ebpf.ProgramSpec `ebpf:"tp_sys_exit"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events             *ebpf.MapSpec `ebpf:"events"`
	FileTrustedExes    *ebpf.MapSpec `ebpf:"file_trusted_exes"`
	PercpuAcceptBuf    *ebpf.MapSpec `ebpf:"percpu_accept_buf"`
	PercpuBindBuf      *ebpf.MapSpec `ebpf:"percpu_bind_buf"`
	PercpuBuf          *ebpf.MapSpec `ebpf:"percpu_buf"`
	PercpuConnectBuf   *ebpf.MapSpec `ebpf:"percpu_connect_buf"`
	PercpuCredsBuf     *ebpf.MapSpec `ebpf:"percpu_creds_buf"`
	PercpuDnsBuf       *ebpf.MapSpec `ebpf:"percpu_dns_buf"`
	PercpuDnsData      *ebpf.MapSpec `ebpf:"percpu_dns_data"`
	PercpuFileBuf      *ebpf.MapSpec `ebpf:"percpu_file_buf"`
	PercpuFilePathBuf  *ebpf.MapSpec `ebpf:"percpu_file_path_buf"`
	PercpuPathBuf      *ebpf.MapSpec `ebpf:"percpu_path_buf"`
	PercpuStdioPathBuf *ebpf.MapSpec `ebpf:"percpu_stdio_path_buf"`
	TrustedExes        *ebpf.MapSpec `ebpf:"trusted_exes"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events             *ebpf.Map `ebpf:"events"`
	FileTrustedExes    *ebpf.Map `ebpf:"file_trusted_exes"`
	PercpuAcceptBuf    *ebpf.Map `ebpf:"percpu_accept_buf"`
	PercpuBindBuf      *ebpf.Map `ebpf:"percpu_bind_buf"`
	PercpuBuf          *ebpf.Map `ebpf:"percpu_buf"`
	PercpuConnectBuf   *ebpf.Map `ebpf:"percpu_connect_buf"`
	PercpuCredsBuf     *ebpf.Map `ebpf:"percpu_creds_buf"`
	PercpuDnsBuf       *ebpf.Map `ebpf:"percpu_dns_buf"`
	PercpuDnsData      *ebpf.Map `ebpf:"percpu_dns_data"`
	PercpuFileBuf      *ebpf.Map `ebpf:"percpu_file_buf"`
	PercpuFilePathBuf  *ebpf.Map `ebpf:"percpu_file_path_buf"`
	PercpuPathBuf      *ebpf.Map `ebpf:"percpu_path_buf"`
	PercpuStdioPathBuf *ebpf.Map `ebpf:"percpu_stdio_path_buf"`
	TrustedExes        *ebpf.Map `ebpf:"trusted_exes"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.FileTrustedExes,
		m.PercpuAcceptBuf,
		m.PercpuBindBuf,
		m.PercpuBuf,
		m.PercpuConnectBuf,
		m.PercpuCredsBuf,
		m.PercpuDnsBuf,
		m.PercpuDnsData,
		m.PercpuFileBuf,
		m.PercpuFilePathBuf,
		m.PercpuPathBuf,
		m.PercpuStdioPathBuf,
		m.TrustedExes,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KpCommitCreds *ebpf.Program `ebpf:"kp_commit_creds"`
	KpInodeCreate *ebpf.Program `ebpf:"kp_inode_create"`
	KpInodeRename *ebpf.Program `ebpf:"kp_inode_rename"`
	KpInodeUnlink *ebpf.Program `ebpf:"kp_inode_unlink"`
	TpProcExec    *ebpf.Program `ebpf:"tp_proc_exec"`
	TpSysExit     *ebpf.Program `ebpf:"tp_sys_exit"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KpCommitCreds,
		p.KpInodeCreate,
		p.KpInodeRename,
		p.KpInodeUnlink,
		p.TpProcExec,
		p.TpSysExit,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
