// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfCommitCredsEvent struct {
	EventType uint8
	Padding1  [3]uint8
	Pid       uint32
	Tgid      uint32
	Ppid      uint32
	Uid       uint32
	OldUid    uint32
	OldEuid   uint32
	NewUid    uint32
	NewEuid   uint32
	Comm      [16]int8
	ExePath   [256]int8
}

type bpfExeItem struct {
	Len  int32
	Sid  uint32
	Hash uint64
	Name [2048]int8
}

type bpfExecveEvent struct {
	EventType uint8
	Padding1  [3]uint8
	Pid       uint32
	Tgid      uint32
	Ppid      uint32
	Pgid      uint32
	Uid       uint32
	Padding   uint32
	Comm      [16]int8
	ExePath   [256]int8
	Args      [512]int8
}

type bpfPathBuf struct {
	Data [512]int8
	Swap [260]int8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KpCommitCreds *ebpf.ProgramSpec `ebpf:"kp_commit_creds"`
	TpProcExec    *ebpf.ProgramSpec `ebpf:"tp_proc_exec"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	PercpuBuf      *ebpf.MapSpec `ebpf:"percpu_buf"`
	PercpuCredsBuf *ebpf.MapSpec `ebpf:"percpu_creds_buf"`
	PercpuPathBuf  *ebpf.MapSpec `ebpf:"percpu_path_buf"`
	TrustedExes    *ebpf.MapSpec `ebpf:"trusted_exes"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	PercpuBuf      *ebpf.Map `ebpf:"percpu_buf"`
	PercpuCredsBuf *ebpf.Map `ebpf:"percpu_creds_buf"`
	PercpuPathBuf  *ebpf.Map `ebpf:"percpu_path_buf"`
	TrustedExes    *ebpf.Map `ebpf:"trusted_exes"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.PercpuBuf,
		m.PercpuCredsBuf,
		m.PercpuPathBuf,
		m.TrustedExes,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KpCommitCreds *ebpf.Program `ebpf:"kp_commit_creds"`
	TpProcExec    *ebpf.Program `ebpf:"tp_proc_exec"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KpCommitCreds,
		p.TpProcExec,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
